// AUTO-GENERATED by scripts/gen-settings-registry.mjs — DO NOT EDIT
// Re-generate with: npm run gen:settings

import type { SettingEntry } from './settingsTypes'

export const SETTINGS_REGISTRY: SettingEntry[] = 
[
  {
    "id": "about.auto-update-on-restart",
    "label": "Auto-update on restart",
    "labelKey": "pages.settings.aboutPanel.auto_update_on_restart",
    "tab": "about",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "about.update-notifications",
    "labelKey": "pages.settings.aboutPanel.notify_when_an_update_is_available",
    "tab": "about",
    "type": "toggle",
    "occurrence": 1,
    "configKey": "auto_update",
    "label": "Notify when an update is available"
  },
  {
    "id": "about.update-channel",
    "labelKey": "pages.settings.aboutPanel.update_channel",
    "tab": "about",
    "type": "buttonGroup",
    "occurrence": 1,
    "label": "Update channel"
  },
  {
    "id": "browser.attach-token",
    "labelKey": "pages.settings.browserPanel.token_label",
    "tab": "browser",
    "type": "input",
    "occurrence": 1,
    "label": "Extension token (optional)"
  },
  {
    "id": "browser.use-the-built-in-browser",
    "label": "Use the built-in browser",
    "labelKey": "pages.settings.browserPanel.use_builtin_label",
    "tab": "browser",
    "type": "toggle",
    "occurrence": 1,
    "configKey": "dashboard.use_builtin_browser"
  },
  {
    "id": "channels.allowed-emails-webex",
    "label": "Allowed emails (Webex)",
    "labelKey": "pages.settings.webexPanel.allowed_emails",
    "labelSuffix": "Webex",
    "description": "Webex account emails permitted to DM the bot. Empty = nobody (fail closed) — anyone in an org can message a Webex bot, so add only your own.",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "webex"
    }
  },
  {
    "id": "channels.allowed-enterprise-orgs-slack",
    "label": "Allowed enterprise orgs (Slack)",
    "labelKey": "pages.settings.slackPanel.allowed_enterprise_orgs",
    "labelSuffix": "Slack",
    "description": "Enterprise Grid org IDs to allow (starts with E or T). Leave empty to allow all orgs.",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "slack"
    }
  },
  {
    "id": "channels.allowed-handles-imessage",
    "label": "Allowed handles (iMessage)",
    "labelKey": "pages.settings.iMessagePanel.allowed_handles",
    "labelSuffix": "iMessage",
    "description": "Phone numbers or Apple Account emails allowed to message the agent. Empty denies everyone — anyone who knows this Mac's handle can send to it, so there is no safe default. Formatting is ignored.",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "imessage"
    }
  },
  {
    "id": "channels.allowed-numbers-whatsapp",
    "label": "Allowed numbers (WhatsApp)",
    "labelKey": "pages.settings.whatsAppPanel.allowed_wa_ids",
    "labelSuffix": "WhatsApp",
    "description": "Phone numbers (digits with country code, no plus sign) that may also chat with the agent. Empty adds nobody beyond you.",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "whatsapp"
    }
  },
  {
    "id": "channels.allowed-space-ids-webex",
    "label": "Allowed space IDs (Webex)",
    "labelKey": "pages.settings.webexPanel.allowed_room_ids",
    "labelSuffix": "Webex",
    "description": "Empty means no space is answered, so turning the switch on alone grants nothing. The sender must also be on the allowed-emails list. A space ID is an opaque string — list yours with:\ncurl -H \"Authorization: Bearer $WEBEX_BOT_TOKEN\" https://webexapis.com/v1/rooms",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "webex"
    }
  },
  {
    "id": "channels.allowed-user-ids-discord",
    "label": "Allowed user IDs (Discord)",
    "labelKey": "pages.settings.botChannelPanel.allowed_user_ids",
    "labelSuffix": "Discord",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "discord"
    }
  },
  {
    "id": "channels.allowed-user-ids-telegram",
    "label": "Allowed user IDs (Telegram)",
    "labelKey": "pages.settings.botChannelPanel.allowed_user_ids",
    "labelSuffix": "Telegram",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "telegram"
    }
  },
  {
    "id": "channels.allowed-user-ids-wechat",
    "label": "Allowed user IDs (WeChat)",
    "labelKey": "pages.settings.weixinPanel.allowed_user_ids",
    "labelSuffix": "WeChat",
    "description": "Allowed WeChat user IDs. Empty = deny all (fail closed).",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "weixin"
    }
  },
  {
    "id": "channels.allowed-user-ids-wecom",
    "label": "Allowed user IDs (WeCom)",
    "labelKey": "pages.settings.botChannelPanel.allowed_user_ids",
    "labelSuffix": "WeCom",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "wecom"
    }
  },
  {
    "id": "channels.allowed-users-email-or-aad-object-id-teams",
    "label": "Allowed users (email or AAD object id) (Teams)",
    "labelKey": "pages.settings.teamsPanel.allowed_users_email_or_aad_object_id",
    "labelSuffix": "Teams",
    "description": "Azure AD UPNs/emails OR object ids permitted to DM the bot. Teams activities reliably carry the object id (email is often absent), so object ids work out of the box. Empty = nobody (fail closed).",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "teams"
    }
  },
  {
    "id": "channels.answer-in-group-spaces-webex",
    "label": "Answer in group spaces (Webex)",
    "labelKey": "pages.settings.webexPanel.allow_group_spaces",
    "labelSuffix": "Webex",
    "description": "Off by default. A reply in a space is visible to everyone in it, including people not on the allowed-emails list.",
    "tab": "channels",
    "type": "toggle",
    "occurrence": 1,
    "params": {
      "channel": "webex"
    }
  },
  {
    "id": "channels.app-client-id-teams",
    "label": "App (Client) ID (Teams)",
    "labelKey": "pages.settings.teamsPanel.app_client_id",
    "labelSuffix": "Teams",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "teams"
    },
    "configKey": "teams.app_id"
  },
  {
    "id": "channels.app-password-client-secret-teams",
    "label": "App password (client secret) (Teams)",
    "labelKey": "pages.settings.teamsPanel.app_password_client_secret",
    "labelSuffix": "Teams",
    "description": "Azure Bot client secret. Stored only in .env (never config.json).",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "teams"
    }
  },
  {
    "id": "channels.enable-imessage-channel-imessage",
    "label": "Enable iMessage channel (iMessage)",
    "labelKey": "pages.settings.iMessagePanel.enable",
    "labelSuffix": "iMessage",
    "description": "Start the channel at gateway boot on this Mac.",
    "tab": "channels",
    "type": "toggle",
    "occurrence": 1,
    "params": {
      "channel": "imessage"
    }
  },
  {
    "id": "channels.enable-teams-channel-teams",
    "label": "Enable Teams channel (Teams)",
    "labelKey": "pages.settings.teamsPanel.enable_teams_channel",
    "labelSuffix": "Teams",
    "description": "Start the channel at gateway boot when the App ID + password are set.",
    "tab": "channels",
    "type": "toggle",
    "occurrence": 1,
    "params": {
      "channel": "teams"
    }
  },
  {
    "id": "channels.enable-the-wechat-channel-wechat",
    "label": "Enable the WeChat channel (WeChat)",
    "labelKey": "pages.settings.weixinPanel.enable_the_wechat_channel",
    "labelSuffix": "WeChat",
    "tab": "channels",
    "type": "toggle",
    "occurrence": 1,
    "params": {
      "channel": "weixin"
    }
  },
  {
    "id": "channels.enable-the-whatsapp-channel-whatsapp",
    "label": "Enable the WhatsApp channel (WhatsApp)",
    "labelKey": "pages.settings.whatsAppPanel.enable_the_whatsapp_channel",
    "labelSuffix": "WhatsApp",
    "tab": "channels",
    "type": "toggle",
    "occurrence": 1,
    "params": {
      "channel": "whatsapp"
    }
  },
  {
    "id": "channels.enable-webex-channel-webex",
    "label": "Enable Webex channel (Webex)",
    "labelKey": "pages.settings.webexPanel.enable_webex_channel",
    "labelSuffix": "Webex",
    "description": "Start the channel at gateway boot when a token is set.",
    "tab": "channels",
    "type": "toggle",
    "occurrence": 1,
    "params": {
      "channel": "webex"
    }
  },
  {
    "id": "channels.file-sessions-in-a-folder-discord",
    "label": "File sessions in a folder (Discord)",
    "labelKey": "pages.settings.botChannelPanel.file_sessions_in_folder",
    "labelSuffix": "Discord",
    "tab": "channels",
    "type": "toggle",
    "occurrence": 1,
    "params": {
      "channel": "discord"
    }
  },
  {
    "id": "channels.file-sessions-in-a-folder-imessage",
    "label": "File sessions in a folder (iMessage)",
    "labelKey": "pages.settings.botChannelPanel.file_sessions_in_folder",
    "labelSuffix": "iMessage",
    "tab": "channels",
    "type": "toggle",
    "occurrence": 1,
    "params": {
      "channel": "imessage"
    }
  },
  {
    "id": "channels.file-sessions-in-a-folder-slack",
    "label": "File sessions in a folder (Slack)",
    "labelKey": "pages.settings.botChannelPanel.file_sessions_in_folder",
    "labelSuffix": "Slack",
    "tab": "channels",
    "type": "toggle",
    "occurrence": 1,
    "params": {
      "channel": "slack"
    }
  },
  {
    "id": "channels.file-sessions-in-a-folder-teams",
    "label": "File sessions in a folder (Teams)",
    "labelKey": "pages.settings.botChannelPanel.file_sessions_in_folder",
    "labelSuffix": "Teams",
    "tab": "channels",
    "type": "toggle",
    "occurrence": 1,
    "params": {
      "channel": "teams"
    }
  },
  {
    "id": "channels.file-sessions-in-a-folder-telegram",
    "label": "File sessions in a folder (Telegram)",
    "labelKey": "pages.settings.botChannelPanel.file_sessions_in_folder",
    "labelSuffix": "Telegram",
    "tab": "channels",
    "type": "toggle",
    "occurrence": 1,
    "params": {
      "channel": "telegram"
    }
  },
  {
    "id": "channels.file-sessions-in-a-folder-webex",
    "label": "File sessions in a folder (Webex)",
    "labelKey": "pages.settings.botChannelPanel.file_sessions_in_folder",
    "labelSuffix": "Webex",
    "tab": "channels",
    "type": "toggle",
    "occurrence": 1,
    "params": {
      "channel": "webex"
    }
  },
  {
    "id": "channels.file-sessions-in-a-folder-wechat",
    "label": "File sessions in a folder (WeChat)",
    "labelKey": "pages.settings.botChannelPanel.file_sessions_in_folder",
    "labelSuffix": "WeChat",
    "tab": "channels",
    "type": "toggle",
    "occurrence": 1,
    "params": {
      "channel": "weixin"
    }
  },
  {
    "id": "channels.file-sessions-in-a-folder-wecom",
    "label": "File sessions in a folder (WeCom)",
    "labelKey": "pages.settings.botChannelPanel.file_sessions_in_folder",
    "labelSuffix": "WeCom",
    "tab": "channels",
    "type": "toggle",
    "occurrence": 1,
    "params": {
      "channel": "wecom"
    }
  },
  {
    "id": "channels.file-sessions-in-a-folder-whatsapp",
    "label": "File sessions in a folder (WhatsApp)",
    "labelKey": "pages.settings.botChannelPanel.file_sessions_in_folder",
    "labelSuffix": "WhatsApp",
    "tab": "channels",
    "type": "toggle",
    "occurrence": 1,
    "params": {
      "channel": "whatsapp"
    }
  },
  {
    "id": "channels.folder-name-discord",
    "label": "Folder name (Discord)",
    "labelKey": "pages.settings.botChannelPanel.session_folder_name",
    "labelSuffix": "Discord",
    "description": "Created for you when you save these settings, if it does not exist yet.",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "discord"
    }
  },
  {
    "id": "channels.folder-name-imessage",
    "label": "Folder name (iMessage)",
    "labelKey": "pages.settings.botChannelPanel.session_folder_name",
    "labelSuffix": "iMessage",
    "description": "Created for you when you save these settings, if it does not exist yet.",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "imessage"
    }
  },
  {
    "id": "channels.folder-name-slack",
    "label": "Folder name (Slack)",
    "labelKey": "pages.settings.botChannelPanel.session_folder_name",
    "labelSuffix": "Slack",
    "description": "Created for you when you save these settings, if it does not exist yet.",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "slack"
    }
  },
  {
    "id": "channels.folder-name-teams",
    "label": "Folder name (Teams)",
    "labelKey": "pages.settings.botChannelPanel.session_folder_name",
    "labelSuffix": "Teams",
    "description": "Created for you when you save these settings, if it does not exist yet.",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "teams"
    }
  },
  {
    "id": "channels.folder-name-telegram",
    "label": "Folder name (Telegram)",
    "labelKey": "pages.settings.botChannelPanel.session_folder_name",
    "labelSuffix": "Telegram",
    "description": "Created for you when you save these settings, if it does not exist yet.",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "telegram"
    }
  },
  {
    "id": "channels.folder-name-webex",
    "label": "Folder name (Webex)",
    "labelKey": "pages.settings.botChannelPanel.session_folder_name",
    "labelSuffix": "Webex",
    "description": "Created for you when you save these settings, if it does not exist yet.",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "webex"
    }
  },
  {
    "id": "channels.folder-name-wechat",
    "label": "Folder name (WeChat)",
    "labelKey": "pages.settings.botChannelPanel.session_folder_name",
    "labelSuffix": "WeChat",
    "description": "Created for you when you turn this on, if it does not exist yet.",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "weixin"
    }
  },
  {
    "id": "channels.folder-name-wecom",
    "label": "Folder name (WeCom)",
    "labelKey": "pages.settings.botChannelPanel.session_folder_name",
    "labelSuffix": "WeCom",
    "description": "Created for you when you save these settings, if it does not exist yet.",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "wecom"
    }
  },
  {
    "id": "channels.folder-name-whatsapp",
    "label": "Folder name (WhatsApp)",
    "labelKey": "pages.settings.botChannelPanel.session_folder_name",
    "labelSuffix": "WhatsApp",
    "description": "Created for you when you turn this on, if it does not already exist.",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "whatsapp"
    }
  },
  {
    "id": "channels.hard-context-threshold-teams",
    "label": "Hard context threshold % (Teams)",
    "labelKey": "pages.settings.channels.hard_threshold_label",
    "labelSuffix": "Teams",
    "description": "Compact automatically at this percentage, even without a reply, so the context window never overflows.",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "teams"
    },
    "configKey": "teams.hard_threshold_pct"
  },
  {
    "id": "channels.hard-context-threshold-webex",
    "label": "Hard context threshold % (Webex)",
    "labelKey": "pages.settings.webexPanel.hard_context_threshold",
    "labelSuffix": "Webex",
    "description": "Compact automatically at this point, even without a decision, so the context window never overflows.",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "webex"
    }
  },
  {
    "id": "channels.how-the-agent-joins-in-whatsapp",
    "label": "How the agent joins in (WhatsApp)",
    "labelKey": "pages.settings.whatsAppPanel.how_the_agent_joins_in",
    "labelSuffix": "WhatsApp",
    "tab": "channels",
    "type": "select",
    "occurrence": 1,
    "params": {
      "channel": "whatsapp"
    }
  },
  {
    "id": "channels.messages-database-path-imessage",
    "label": "Messages database path (iMessage)",
    "labelKey": "pages.settings.iMessagePanel.db_path",
    "labelSuffix": "iMessage",
    "description": "Override where the Messages database is read from. Leave empty to use the default location.",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "imessage"
    }
  },
  {
    "id": "channels.owner-slack-member-id-slack",
    "label": "Owner Slack member ID (Slack)",
    "labelKey": "pages.settings.slackPanel.owner_slack_member_id",
    "labelSuffix": "Slack",
    "description": "The one member who can always interact with the bot (KIROCREW_OWNER_ID). Starts with U or W.",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "slack"
    }
  },
  {
    "id": "channels.phase-reactions-slack",
    "label": "Phase reactions (Slack)",
    "labelKey": "pages.settings.slackPanel.phase_reactions",
    "labelSuffix": "Slack",
    "description": "Show phase-aware emoji reactions (queued → thinking → coding → done) on messages.",
    "tab": "channels",
    "type": "toggle",
    "occurrence": 1,
    "params": {
      "channel": "slack"
    }
  },
  {
    "id": "channels.reply-in-thread-webex",
    "label": "Reply in thread (Webex)",
    "labelKey": "pages.settings.webexPanel.reply_in_thread",
    "labelSuffix": "Webex",
    "description": "Reply under the message's own thread when it has one, which keeps a busy space readable.",
    "tab": "channels",
    "type": "toggle",
    "occurrence": 1,
    "params": {
      "channel": "webex"
    }
  },
  {
    "id": "channels.seconds-between-unprompted-replies-whatsapp",
    "label": "Seconds between unprompted replies (WhatsApp)",
    "labelKey": "pages.settings.whatsAppPanel.seconds_between_unprompted_replies",
    "labelSuffix": "WhatsApp",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "whatsapp"
    }
  },
  {
    "id": "channels.send-replies-over-imessage",
    "label": "Send replies over (iMessage)",
    "labelKey": "pages.settings.iMessagePanel.service",
    "labelSuffix": "iMessage",
    "description": "Which service outbound replies use. Inbound is unaffected — messages are accepted whichever service they arrive over.",
    "tab": "channels",
    "type": "select",
    "occurrence": 1,
    "params": {
      "channel": "imessage"
    }
  },
  {
    "id": "channels.show-thinking-slack",
    "label": "Show thinking (Slack)",
    "labelKey": "pages.settings.slackPanel.show_thinking",
    "labelSuffix": "Slack",
    "description": "Post the model's reasoning as a thread reply. Disable to keep responses concise.",
    "tab": "channels",
    "type": "toggle",
    "occurrence": 1,
    "params": {
      "channel": "slack"
    }
  },
  {
    "id": "channels.slack-app-token-slack",
    "label": "Slack app token (Slack)",
    "labelKey": "pages.settings.slackPanel.slack_app_token",
    "labelSuffix": "Slack",
    "description": "App-level token required for Socket Mode (starts with xapp-).",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "slack"
    }
  },
  {
    "id": "channels.slack-bot-token-slack",
    "label": "Slack bot token (Slack)",
    "labelKey": "pages.settings.slackPanel.slack_bot_token",
    "labelSuffix": "Slack",
    "description": "From OAuth & Permissions after installing your Slack app (starts with xoxb-).",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "slack"
    }
  },
  {
    "id": "channels.slash-command-slack",
    "label": "Slash command (Slack)",
    "labelKey": "pages.settings.slackPanel.slash_command",
    "labelSuffix": "Slack",
    "description": "Trigger word for the Slack slash command (without the leading /).",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "slack"
    }
  },
  {
    "id": "channels.soft-context-threshold-discord",
    "label": "Soft context threshold % (Discord)",
    "labelKey": "pages.settings.botChannelPanel.soft_context_threshold",
    "labelSuffix": "Discord",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "discord"
    }
  },
  {
    "id": "channels.soft-context-threshold-teams",
    "label": "Soft context threshold % (Teams)",
    "labelKey": "pages.settings.botChannelPanel.soft_context_threshold",
    "labelSuffix": "Teams",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "teams"
    },
    "configKey": "teams.soft_threshold_pct"
  },
  {
    "id": "channels.soft-context-threshold-telegram",
    "label": "Soft context threshold % (Telegram)",
    "labelKey": "pages.settings.botChannelPanel.soft_context_threshold",
    "labelSuffix": "Telegram",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "telegram"
    }
  },
  {
    "id": "channels.soft-context-threshold-webex",
    "label": "Soft context threshold % (Webex)",
    "labelKey": "pages.settings.webexPanel.soft_context_threshold",
    "labelSuffix": "Webex",
    "description": "When a conversation's context passes this, suggest /compact or /new instead of compacting automatically.",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "webex"
    }
  },
  {
    "id": "channels.soft-context-threshold-wecom",
    "label": "Soft context threshold % (WeCom)",
    "labelKey": "pages.settings.botChannelPanel.soft_context_threshold",
    "labelSuffix": "WeCom",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "wecom"
    }
  },
  {
    "id": "channels.tenant-id-teams",
    "label": "Tenant ID (Teams)",
    "labelKey": "pages.settings.teamsPanel.tenant_id",
    "labelSuffix": "Teams",
    "description": "Optional — only for single-tenant bots.",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "teams"
    },
    "configKey": "teams.tenant_id"
  },
  {
    "id": "channels.webex-bot-token-webex",
    "label": "Webex bot token (Webex)",
    "labelKey": "pages.settings.webexPanel.webex_bot_token",
    "labelSuffix": "Webex",
    "description": "Bot access token from developer.webex.com (My Webex Apps).",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "webex"
    }
  },
  {
    "id": "channels.when-the-agent-may-speak-whatsapp",
    "label": "When the agent may speak (WhatsApp)",
    "labelKey": "pages.settings.whatsAppPanel.when_the_agent_may_speak",
    "labelSuffix": "WhatsApp",
    "tab": "channels",
    "type": "input",
    "occurrence": 1,
    "params": {
      "channel": "whatsapp"
    }
  },
  {
    "id": "channels.who-can-message-the-agent-whatsapp",
    "label": "Who can message the agent (WhatsApp)",
    "labelKey": "pages.settings.whatsAppPanel.who_can_message_the_bot",
    "labelSuffix": "WhatsApp",
    "tab": "channels",
    "type": "select",
    "occurrence": 1,
    "params": {
      "channel": "whatsapp"
    }
  },
  {
    "id": "channels.who-can-message-the-bot-wechat",
    "label": "Who can message the bot (WeChat)",
    "labelKey": "pages.settings.weixinPanel.who_can_message_the_bot",
    "labelSuffix": "WeChat",
    "tab": "channels",
    "type": "select",
    "occurrence": 1,
    "params": {
      "channel": "weixin"
    }
  },
  {
    "id": "chat.auto-compact-threshold",
    "label": "Auto-Compact Threshold",
    "labelKey": "pages.settings.chatPanel.auto_compact_threshold",
    "description": "Context usage % at which auto-compaction triggers. Lower = more frequent compaction, longer sessions",
    "tab": "chat",
    "type": "select",
    "occurrence": 1,
    "configKey": "session.autocompact_pct"
  },
  {
    "id": "chat.auto-open-git-in-side-panel",
    "label": "Auto-Open Git in Side Panel",
    "labelKey": "pages.settings.chatPanel.auto_open_git_panel",
    "description": "Expand the side panel to the Git tab each time you start a chat in a git project. The Git tab is created either way.",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.background-effort",
    "label": "Background Effort",
    "labelKey": "pages.settings.chatPanel.background_effort",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "chat.background-model",
    "label": "Background Model",
    "labelKey": "pages.settings.chatPanel.background_model",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "chat.compact-empty-folders",
    "label": "Compact Empty Folders",
    "labelKey": "pages.settings.chatPanel.compact_empty_folders",
    "description": "A folder with no chats takes one row instead of two, and its New chat button moves onto the folder's own row",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.completion-event-characters",
    "label": "Completion Event Characters",
    "labelKey": "pages.settings.chatPanel.completion_event_characters",
    "tab": "chat",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "chat.completion-event-truncation",
    "label": "Completion Event Truncation",
    "labelKey": "pages.settings.chatPanel.completion_event_truncation",
    "description": "Which part of a subagent's stream to keep when injecting its completion event into the parent session. Head preserves the start (default, matches legacy behavior). Tail preserves the final summary. Both keeps a slice from each end with a marker between them.",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "chat.confirm-before-closing-session",
    "label": "Confirm Before Closing Session",
    "labelKey": "pages.settings.chatPanel.confirm_before_closing_session",
    "description": "Show a confirmation dialog when closing a session",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.content-width",
    "label": "Content Width",
    "labelKey": "pages.settings.chatPanel.content_width",
    "description": "Compact is the original view. Comfortable and Full use more screen space.",
    "tab": "chat",
    "type": "buttonGroup",
    "occurrence": 1
  },
  {
    "id": "chat.content-filter-fallback-model",
    "label": "Content-filter fallback model",
    "labelKey": "pages.settings.chatPanel.refusal_fallback_model",
    "tab": "chat",
    "type": "select",
    "occurrence": 1,
    "configKey": "agent.refusal_fallback_model"
  },
  {
    "id": "chat.default-memory-mode",
    "label": "Default Memory Mode",
    "labelKey": "settings.chat.defaultMemoryMode.label",
    "description": "Persistent uses what it knows and saves new memory. Incognito uses what it knows but saves no new memory. Temporary starts blank and saves no new memory. Every chat still appears in History. You can change the mode for any chat.",
    "tab": "chat",
    "type": "select",
    "occurrence": 1,
    "configKey": "dashboard.default_memory_mode"
  },
  {
    "id": "chat.default-model",
    "label": "Default Model",
    "labelKey": "pages.settings.chatPanel.default_model",
    "description": "Which model new sessions start with when their agent pins none. Set a model per agent under Capabilities → Agents, or pick one inside a session to override it there.",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "chat.default-reasoning-effort",
    "label": "Default Reasoning Effort",
    "labelKey": "pages.settings.chatPanel.default_reasoning_effort",
    "description": "How long models think before answering by default. Higher is slower and costs more. Only available on reasoning-capable models (Opus, Sonnet, Fable, GPT-5.x).",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "chat.default-to-autopilot-mode",
    "label": "Default to Autopilot Mode",
    "labelKey": "pages.settings.chatPanel.default_to_autopilot_mode",
    "description": "New sessions start in autopilot mode (plan → approve → execute). You can still toggle individual sessions.",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.describe-your-role",
    "label": "Describe your role",
    "labelKey": "pages.settings.chatPanel.describe_your_role",
    "description": "Kiro uses this description to adapt vocabulary and examples to your role.",
    "tab": "chat",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "chat.fallback-model",
    "label": "Fallback model",
    "labelKey": "pages.settings.chatPanel.fallback_model",
    "tab": "chat",
    "type": "select",
    "occurrence": 1,
    "configKey": "agent.fallback_model"
  },
  {
    "id": "chat.feature-tips",
    "label": "Feature Tips",
    "labelKey": "pages.settings.chatPanel.feature_tips",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.file-change-chips",
    "label": "File Change Chips",
    "labelKey": "pages.settings.chatPanel.file_change_chips",
    "description": "How file diff chips appear below assistant messages",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "chat.folder-suggestions",
    "label": "Folder suggestions",
    "labelKey": "pages.settings.chatPanel.folder_suggestions",
    "description": "Offer to file a new session into a matching folder once it has a title.",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.follow-up-bar-layout",
    "label": "Follow-Up Bar Layout",
    "labelKey": "pages.settings.chatPanel.follow_up_bar_layout",
    "description": "Multiline wraps suggestions onto multiple rows. Single line keeps them on one horizontally-scrollable row.",
    "tab": "chat",
    "type": "buttonGroup",
    "occurrence": 1
  },
  {
    "id": "chat.history-expanded",
    "label": "History Expanded",
    "labelKey": "pages.settings.chatPanel.history_expanded",
    "description": "Expand history sidebar by default",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.link-previews",
    "label": "Link Previews",
    "labelKey": "pages.settings.chatPanel.link_previews",
    "description": "Show a favicon and page title instead of the raw URL. This machine then fetches every link the model outputs, so each linked site sees a request from your IP address.",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.mcp-apps-in-side-panel",
    "label": "MCP Apps in Side Panel",
    "labelKey": "pages.settings.chatPanel.mcp_apps_in_side_panel",
    "description": "Render interactive MCP Apps (such as Excalidraw diagrams) in the right side panel instead of inline in the chat. The panel opens automatically.",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.merge-queued-messages",
    "label": "Merge Queued Messages",
    "labelKey": "pages.settings.chatPanel.merge_queued_messages",
    "description": "Combine follow-up messages into a single labeled prompt while the agent is busy",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.pin-the-latest-turn",
    "label": "Pin the latest turn",
    "labelKey": "pages.settings.chatPanel.pin_last_prompt",
    "description": "Keep the most recent turn visible as a sticky banner once it scrolls above the fold.",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.plain-diffs",
    "label": "Plain diffs",
    "labelKey": "settings.chat.plainDiff.label",
    "description": "Render diffs as plain unified-diff text instead of syntax-highlighted colour. Uses less memory on large diffs.",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.pr-and-issue-chips-on-session-cards",
    "label": "PR and Issue Chips on Session Cards",
    "labelKey": "pages.settings.chatPanel.session_card_source_links",
    "description": "Show a chip on each session's sidebar card for every pull request, merge request and issue mentioned in that session. Turning it off also stops the periodic provider calls that keep those chips up to date.",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.prevent-sleep-while-running",
    "label": "Prevent sleep while running",
    "labelKey": "pages.settings.chatPanel.prevent_sleep_while_running",
    "description": "Keep your computer awake while a task is running",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1,
    "configKey": "dashboard.prevent_sleep"
  },
  {
    "id": "chat.quick-send",
    "label": "Quick Send",
    "labelKey": "pages.settings.chatPanel.quick_send",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.response-verbosity",
    "label": "Response Verbosity",
    "labelKey": "pages.settings.chatPanel.response_verbosity",
    "description": "How terse the agent's prose is. Ultra-concise keeps the whole reply short: answer first, bullets over paragraphs, no filler. Code, commands, and error strings stay verbatim at every level; security warnings always appear but stay brief, and multi-step instructions stay complete. Answer-only goes further and drops explanation entirely: one sentence at most, and detail only when you ask for it — or when a decision is consequential enough (security, exposure, data loss, spend, anything hard to undo) that you need the reasoning to choose correctly.",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "chat.restore-sessions",
    "label": "Restore Sessions",
    "labelKey": "pages.settings.chatPanel.restore_sessions",
    "description": "Re-open recently active sessions on startup",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.restore-window",
    "label": "Restore Window",
    "labelKey": "pages.settings.chatPanel.restore_window",
    "description": "Time window for session restoration",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "chat.selectable-models",
    "label": "Selectable Models",
    "labelKey": "pages.settings.chatPanel.selectable_models",
    "description": "Choose which advertised models appear in Chat model pickers. Auto and an active session model always remain visible.",
    "tab": "chat",
    "type": "select",
    "occurrence": 1,
    "configKey": "dashboard.model_picker_hidden_models",
    "settingId": "chat.selectable-models"
  },
  {
    "id": "chat.send-shortcut",
    "label": "Send shortcut",
    "labelKey": "pages.settings.chatPanel.send_shortcut",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "chat.session-summaries",
    "label": "Session summaries",
    "labelKey": "pages.settings.chatPanel.session_summaries",
    "description": "Summarize each session by intent. Uses tokens on turns that change the session.",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.show-context-percentage",
    "label": "Show Context Percentage",
    "labelKey": "pages.settings.chatPanel.show_context_percentage",
    "description": "Display usage percentage next to the context progress bar",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.show-context-tokens",
    "label": "Show Context Tokens",
    "labelKey": "pages.settings.chatPanel.show_token_usage",
    "description": "Display used and total tokens next to the context progress bar",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.show-pasted-text-in-full",
    "label": "Show Pasted Text in Full",
    "labelKey": "pages.settings.chatPanel.show_pasted_text_in_full",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.show-thinking-inline",
    "label": "Show Thinking Inline",
    "labelKey": "pages.settings.chatPanel.show_thinking_inline",
    "description": "Show intermediate reasoning text between tool calls instead of collapsing everything",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.show-timestamps",
    "label": "Show Timestamps",
    "labelKey": "pages.settings.chatPanel.show_timestamps",
    "description": "Display time on each message",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.simplified-tool-call-names",
    "label": "Simplified Tool Call Names",
    "labelKey": "pages.settings.chatPanel.simplified_tool_call_names",
    "description": "When enabled, inline tool pills show simplified tool use purpose instead of the exact command being run",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.soft-stop-budget-seconds",
    "label": "Soft-stop budget (seconds)",
    "labelKey": "pages.settings.chatPanel.soft_stop_budget_seconds",
    "tab": "chat",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "chat.spell-check-message-input",
    "label": "Spell Check Message Input",
    "labelKey": "pages.settings.chatPanel.spellcheck_input",
    "description": "Underline misspelled words in the message input with a red squiggle. Turn it off to stop the red underlines while you type.",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.split-side-by-side-diffs",
    "label": "Split (side-by-side) diffs",
    "labelKey": "settings.chat.diffLayout.label",
    "description": "Show old and new code in two columns; off shows one unified column. Changing it here or on any diff sets it everywhere.",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.split-view-session-grid",
    "label": "Split View (Session Grid)",
    "labelKey": "pages.settings.chatPanel.split_view_session_grid",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.subagent-effort",
    "label": "Subagent Effort",
    "labelKey": "pages.settings.chatPanel.subagent_effort",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "chat.subagent-model",
    "label": "Subagent Model",
    "labelKey": "pages.settings.chatPanel.subagent_model",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "chat.tail-only-fork",
    "label": "Tail-only Fork",
    "labelKey": "pages.settings.chatPanel.tail_only_fork",
    "description": "Fork keeps only the messages after the chosen point instead of those up to it.",
    "tab": "chat",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "chat.technical-comfort",
    "label": "Technical Comfort",
    "labelKey": "pages.settings.chatPanel.technical_comfort",
    "description": "Sets how deep explanations go — plain language vs. full technical detail",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "chat.text-link-patterns",
    "label": "Text Link Patterns",
    "labelKey": "pages.settings.chatPanel.link_patterns",
    "tab": "chat",
    "type": "input",
    "occurrence": 1,
    "configKey": "dashboard.link_patterns"
  },
  {
    "id": "chat.text-streaming-style",
    "label": "Text Streaming Style",
    "labelKey": "pages.settings.chatPanel.text_streaming_style",
    "description": "Immediate mode shows raw chunks as they arrive. Smooth mode buffers and fades text in at a steady pace.",
    "tab": "chat",
    "type": "buttonGroup",
    "occurrence": 1
  },
  {
    "id": "chat.what-enter-does-while-the-agent-is-working",
    "label": "What Enter does while the agent is working",
    "labelKey": "pages.settings.chatPanel.what_enter_does_while_the_agent_is_working",
    "tab": "chat",
    "type": "buttonGroup",
    "occurrence": 1
  },
  {
    "id": "chat.widget-density",
    "label": "Widget Density",
    "labelKey": "pages.settings.chatPanel.widget_density",
    "description": "How aggressively the agent uses inline widgets for visual content",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "chat.your-role",
    "label": "Your Role",
    "labelKey": "pages.settings.chatPanel.your_role",
    "description": "Kiro matches vocabulary and examples to your professional background",
    "tab": "chat",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "computer-use.attach-screenshots",
    "label": "Attach screenshots",
    "labelKey": "pages.settings.computerUsePanel.attach_screenshots",
    "description": "Also capture the target window and pass its file path. The accessibility tree stays the primary channel; windows containing a password field are never captured.",
    "tab": "computer-use",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "computer-use.enable-computer-use",
    "label": "Enable computer use",
    "labelKey": "pages.settings.computerUsePanel.enable_computer_use",
    "description": "Let the agent read desktop app windows through accessibility and act on their controls. Off until you turn it on here — an agent cannot enable it.",
    "tab": "computer-use",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "computer-use.max-tree-nodes",
    "label": "Max tree nodes",
    "labelKey": "pages.settings.computerUsePanel.max_tree_nodes",
    "description": "How many controls one window reading returns. A window with more than this gets truncated, and the agent is told so. Raise it for dense apps (a spreadsheet, an IDE); lower it to spend fewer tokens per reading.",
    "tab": "computer-use",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "computer-use.screenshot-width",
    "label": "Screenshot width",
    "labelKey": "pages.settings.computerUsePanel.screenshot_width",
    "description": "Longest edge of the screenshot, in pixels. Smaller is cheaper and faster to read; larger keeps small text legible if the agent has to fall back to the image.",
    "tab": "computer-use",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "computer-use.show-cursor-motion",
    "label": "Show cursor motion",
    "labelKey": "pages.settings.computerUsePanel.show_cursor_motion",
    "description": "Draw a cursor that glides to each target and pulses when it clicks, so you can follow along on screen. Purely visual — it changes nothing about what the agent is allowed to do, and it only appears for clicks that move the real pointer.",
    "tab": "computer-use",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "connections.client-id",
    "label": "Client ID",
    "labelKey": "pages.settings.connectionsPanel.client_id",
    "tab": "connections",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "connections.client-secret",
    "label": "Client secret",
    "labelKey": "pages.settings.connectionsPanel.client_secret",
    "tab": "connections",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "connections.client-secret-2",
    "label": "Client secret",
    "labelKey": "pages.settings.connectionsPanel.client_secret",
    "tab": "connections",
    "type": "input",
    "occurrence": 2
  },
  {
    "id": "connections.oauth-client-github",
    "labelKey": "pages.settings.connectionsPanel.oauth_app",
    "labelSuffix": "GitHub",
    "tab": "connections",
    "type": "input",
    "occurrence": 1,
    "settingId": "connections-oauth-client-github",
    "label": "OAuth app",
    "description": "Client ID, client secret and redirect URI for a provider that needs a registered OAuth app"
  },
  {
    "id": "connections.oauth-client-asana",
    "labelKey": "pages.settings.connectionsPanel.oauth_app",
    "labelSuffix": "Asana",
    "tab": "connections",
    "type": "input",
    "occurrence": 1,
    "settingId": "connections-oauth-client-asana",
    "label": "OAuth app",
    "description": "Client ID, client secret and redirect URI for a provider that needs a registered OAuth app"
  },
  {
    "id": "developer.also-send-the-conversation-and-tool-call-inputs-so-jev-can-score-compaction",
    "label": "Also send the conversation and tool-call inputs so Jev can score compaction",
    "labelKey": "pages.developer.featurePreviewsTab.decisions_compaction",
    "description": "Every time context fills up and Kiro Crew compacts a session automatically, this sends that conversation and the inputs of the tool calls in it to Jev, and asks which ones would have been worth keeping. Tool OUTPUT is never sent — only how many characters it was. Passwords and keys are replaced before anything is sent. It is a measurement: the compaction happens exactly as it does now whatever Jev answers, and the answer appears as one line on the compaction notice. This is the widest of the three, so it is off until you turn it on, even if the switches above are already on.",
    "tab": "developer",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "developer.also-send-tool-call-arguments-so-jev-can-flag-risky-calls",
    "label": "Also send tool-call arguments so Jev can flag risky calls",
    "labelKey": "pages.developer.featurePreviewsTab.decisions_tool_args",
    "description": "In a session that approves its own tool calls, this also sends the name and arguments of each call to Jev, which then puts a note on the ones it thinks are worth a look. Passwords and keys are replaced before anything is sent. It changes nothing about which tool calls are allowed. Off until you turn it on, even if the switch above is already on.",
    "tab": "developer",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "developer.chat-on-a-crew",
    "label": "Chat on a crew",
    "labelKey": "pages.developer.featurePreviewsTab.chat_on_a_crew",
    "description": "Adds “New chat on crew” to the create menu, which starts a session on a remote instance — another machine you have connected under Settings > Remote Instances. Unfinished: the session opens in that instance’s own pane and is not listed in this dashboard’s sessions yet, so to return to it later, switch to that instance’s pane.",
    "tab": "developer",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "developer.crew-members",
    "label": "Crew Members",
    "labelKey": "pages.developer.featurePreviewsTab.crew_members",
    "description": "The Crew Members page: every agent you have, each with its own thread. Still being built, so it is not offered until you turn this on.",
    "tab": "developer",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "developer.decisions-jev",
    "label": "Decisions (Jev)",
    "labelKey": "pages.developer.featurePreviewsTab.decisions",
    "description": "Jev is a small, fast decision model. With this on, Kiro Crew asks Jev which one of your skills fits the message you just sent — or that none does — and uses Jev's pick for the share of your sessions shown under the switch; the rest keep the word-matching rule this build ships with. If Jev is slow, unreachable or answers with nothing usable, that message falls back to the same rule, so a decision never holds up your reply. Each call is also recorded in a log on the machine that runs Kiro Crew, for diagnostics. This switch is saved on the machine that runs Kiro Crew, not in this browser, so it applies on every device you open it from.",
    "tab": "developer",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "developer.developer-mode",
    "label": "Developer Mode",
    "labelKey": "pages.settings.developerPanel.developer_mode",
    "description": "Show Developer page in sidebar with Logs, System metrics, and Memory internals",
    "tab": "developer",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "developer.remote-instance-sessions",
    "label": "Remote instance sessions",
    "labelKey": "pages.developer.featurePreviewsTab.remote_instance_sessions",
    "description": "Merge a connected remote instance's live sessions into the Sessions list, each marked with a server badge. Functional, but not finished.",
    "tab": "developer",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "developer.run-a-local-gateway",
    "label": "Run a local gateway",
    "labelKey": "pages.settings.developerPanel.run_a_local_gateway",
    "description": "Start a gateway on this machine. Turn it off to use Kiro Crew as a client only, connecting to the gateway you have configured instead of running one here. Takes effect next time you open the app.",
    "tab": "developer",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "developer.webhooks",
    "label": "Webhooks",
    "labelKey": "pages.developer.featurePreviewsTab.webhooks",
    "description": "Inbound webhook tokens, registered contexts, and run history. The API works; the page is not finished.",
    "tab": "developer",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "display.command-completion",
    "label": "Command completion",
    "labelKey": "pages.settings.displayPanel.terminal_completion",
    "description": "Show the completion popup while typing in the Terminal. Enter runs the line you typed; to take a suggestion, press ↑/↓ then Enter, or Tab. Off hides the popup; your shell's own Tab completion still works.",
    "tab": "display",
    "type": "toggle",
    "occurrence": 1,
    "configKey": "dashboard.terminal.completion.enabled"
  },
  {
    "id": "display.default-for-new-sessions",
    "labelKey": "pages.settings.displayPanel.default_for_new_sessions",
    "tab": "display",
    "type": "buttonGroup",
    "occurrence": 1,
    "label": "Default for New Sessions",
    "description": "None, auto-cycle, or pick a fixed color."
  },
  {
    "id": "display.default-shell",
    "label": "Default shell",
    "labelKey": "pages.settings.displayPanel.terminal_shell",
    "description": "Shell the built-in terminal launches — an absolute path or a command on PATH. Leave empty to use the system default ($SHELL).",
    "tab": "display",
    "type": "input",
    "occurrence": 1,
    "configKey": "dashboard.terminal.shell"
  },
  {
    "id": "display.display-mode",
    "label": "Display Mode",
    "labelKey": "pages.settings.displayPanel.display_mode",
    "description": "How the session color is applied to the row.",
    "tab": "display",
    "type": "buttonGroup",
    "occurrence": 1
  },
  {
    "id": "display.font",
    "label": "Font",
    "labelKey": "pages.settings.displayPanel.terminal_font_family",
    "description": "Font for the built-in terminal. Pick one installed on the machine you view the dashboard from, or type any font name — a Nerd Font renders Powerline and prompt-theme glyphs.",
    "tab": "display",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "display.font-family",
    "label": "Font Family",
    "labelKey": "pages.settings.displayPanel.font_family",
    "description": "UI font family for the dashboard. Code font follows the active theme, except OpenDyslexic which supplies its own.",
    "tab": "display",
    "type": "buttonGroup",
    "occurrence": 1
  },
  {
    "id": "display.font-size",
    "label": "Font size",
    "labelKey": "pages.settings.displayPanel.terminal_font_size",
    "description": "Text size in the built-in terminal, measured in pixels.",
    "tab": "display",
    "type": "stepper",
    "occurrence": 1
  },
  {
    "id": "display.highlight-recent-sessions",
    "label": "Highlight recent sessions",
    "labelKey": "pages.settings.displayPanel.highlight_recent_sessions",
    "description": "Highlight the N most-recently-active sessions with a graded accent stripe (0 = off). Saved to your Kiro Crew config.",
    "tab": "display",
    "type": "stepper",
    "occurrence": 1
  },
  {
    "id": "display.intensity",
    "label": "Intensity",
    "labelKey": "pages.settings.displayPanel.intensity",
    "description": "How visible the color tint is on sidebar rows.",
    "tab": "display",
    "type": "buttonGroup",
    "occurrence": 1
  },
  {
    "id": "display.interface",
    "label": "Interface",
    "labelKey": "pages.settings.displayPanel.interface",
    "description": "Chat bubbles or CLI-style line-by-line output",
    "tab": "display",
    "type": "buttonGroup",
    "occurrence": 1
  },
  {
    "id": "display.language",
    "label": "Language",
    "labelKey": "settings.display.language.label",
    "description": "Language for the dashboard interface.",
    "tab": "display",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "display.mode",
    "label": "Mode",
    "labelKey": "pages.settings.displayPanel.mode",
    "description": "Light or dark appearance for the dashboard",
    "tab": "display",
    "type": "buttonGroup",
    "occurrence": 1
  },
  {
    "id": "display.palette",
    "label": "Palette",
    "labelKey": "pages.settings.displayPanel.palette",
    "description": "Choose a color palette for your sidebar sessions.",
    "tab": "display",
    "type": "buttonGroup",
    "occurrence": 1
  },
  {
    "id": "display.spend-a-few-credits-to-check-your-balance",
    "label": "Spend a few credits to check your balance",
    "labelKey": "pages.settings.displayPanel.credit_usage_scrape",
    "description": "When your usage data is not available for free, your balance can still be checked by sending one billed message, about every 10 minutes while a dashboard tab is open. Each check spends a small number of credits.",
    "tab": "display",
    "type": "toggle",
    "occurrence": 1,
    "configKey": "dashboard.usage_text_scrape_enabled"
  },
  {
    "id": "display.theme",
    "label": "Theme",
    "labelKey": "pages.settings.displayPanel.theme",
    "description": "Select a theme for the dashboard",
    "tab": "display",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "display.zoom-level",
    "label": "Zoom Level",
    "labelKey": "pages.settings.displayPanel.zoom_level",
    "tab": "display",
    "type": "stepper",
    "occurrence": 1
  },
  {
    "id": "instances.auto-connect-crews",
    "label": "Auto-connect crews",
    "labelKey": "pages.settings.remoteCrewPanel.auto_connect",
    "description": "When on, opening the web app connects every crew automatically, and reconnects them when you come back to the tab. Turn off to connect a crew only when you switch to it.",
    "tab": "instances",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "instances.enable-remote-crew-management",
    "labelKey": "pages.settings.instancesPanel.enable_remote_crew_management",
    "tab": "instances",
    "type": "toggle",
    "occurrence": 1,
    "configKey": "instances.enabled",
    "label": "Enable remote instance management"
  },
  {
    "id": "notifications.sound-category-approval",
    "labelKey": "pages.settings.notificationsPanel.category_approval",
    "tab": "notifications",
    "type": "select",
    "occurrence": 1,
    "label": "Approvals and questions",
    "description": "When the agent needs a tool approval or an answer"
  },
  {
    "id": "notifications.sound-category-turn",
    "labelKey": "pages.settings.notificationsPanel.category_turn",
    "tab": "notifications",
    "type": "select",
    "occurrence": 1,
    "label": "Conversation handoffs",
    "description": "When a conversation finishes or pauses for your input"
  },
  {
    "id": "notifications.sound-category-cron",
    "labelKey": "pages.settings.notificationsPanel.category_cron",
    "tab": "notifications",
    "type": "select",
    "occurrence": 1,
    "label": "Cron",
    "description": "Scheduled job completions"
  },
  {
    "id": "notifications.sound-category-all",
    "labelKey": "pages.settings.notificationsPanel.category_all",
    "tab": "notifications",
    "type": "select",
    "occurrence": 1,
    "label": "Default (all categories)",
    "description": "Fallback sound when no category-specific override is set"
  },
  {
    "id": "notifications.sound-category-heartbeat",
    "labelKey": "pages.settings.notificationsPanel.category_heartbeat",
    "tab": "notifications",
    "type": "select",
    "occurrence": 1,
    "label": "Heartbeat",
    "description": "Heartbeat task results"
  },
  {
    "id": "notifications.notify-when-a-background-chat-finishes",
    "label": "Notify when a background chat finishes",
    "labelKey": "pages.settings.notificationsPanel.notify_when_a_background_chat_finishes",
    "description": "Shows a system notification naming the chat that finished, but only while this window is minimized or behind another app.",
    "tab": "notifications",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "notifications.play-sound-on-new-notifications",
    "label": "Play sound on new notifications",
    "labelKey": "pages.settings.notificationsPanel.play_sound_on_new_notifications",
    "tab": "notifications",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "notifications.sound-category-agent",
    "labelKey": "pages.settings.notificationsPanel.category_agent",
    "tab": "notifications",
    "type": "select",
    "occurrence": 1,
    "label": "Proactive agent messages",
    "description": "When the agent proactively messages you outside a chat"
  },
  {
    "id": "notifications.sound-category-skills",
    "labelKey": "pages.settings.notificationsPanel.category_skills",
    "tab": "notifications",
    "type": "select",
    "occurrence": 1,
    "label": "Skills",
    "description": "New skill candidates awaiting your approval"
  },
  {
    "id": "notifications.sources",
    "labelKey": "pages.settings.notificationsPanel.sources",
    "tab": "notifications",
    "type": "toggle",
    "occurrence": 1,
    "label": "Sources",
    "description": "Mute notification sources or override their priority. Muted notifications stay in history but never badge, sound, or banner."
  },
  {
    "id": "notifications.sound-category-subagent",
    "labelKey": "pages.settings.notificationsPanel.category_subagent",
    "tab": "notifications",
    "type": "select",
    "occurrence": 1,
    "label": "Subagent",
    "description": "Background subagent completions"
  },
  {
    "id": "notifications.sound-category-taskrunner",
    "labelKey": "pages.settings.notificationsPanel.category_taskrunner",
    "tab": "notifications",
    "type": "select",
    "occurrence": 1,
    "label": "Tasks",
    "description": "Task Runner completions"
  },
  {
    "id": "notifications.volume",
    "labelKey": "pages.settings.notificationsPanel.volume",
    "tab": "notifications",
    "type": "stepper",
    "occurrence": 1,
    "label": "Volume"
  },
  {
    "id": "notifications.sound-category-hook",
    "labelKey": "pages.settings.notificationsPanel.category_hook",
    "tab": "notifications",
    "type": "select",
    "occurrence": 1,
    "label": "Webhook",
    "description": "External hook triggers"
  },
  {
    "id": "privacy.record-metrics",
    "label": "Record metrics",
    "labelKey": "pages.settings.privacyPanel.recordMetricsLabel",
    "tab": "privacy",
    "type": "toggle",
    "occurrence": 1,
    "configKey": "telemetry.enabled"
  },
  {
    "id": "privacy.send-anonymous-usage-heartbeat",
    "label": "Send anonymous usage heartbeat",
    "labelKey": "privacyDisclosure.toggleLabel",
    "description": "Saved for future launches.",
    "tab": "privacy",
    "type": "toggle",
    "occurrence": 1,
    "configKey": "telemetry.beacon_enabled"
  },
  {
    "id": "secrets.jira-api-token",
    "labelKey": "settings.secrets.jira_api_token_label",
    "tab": "secrets",
    "type": "input",
    "occurrence": 1,
    "label": "Jira API token",
    "description": "Authenticates Jira issue lookups for the configured instance."
  },
  {
    "id": "secrets.wakatime-api-key",
    "labelKey": "settings.secrets.wakatime_api_key_label",
    "tab": "secrets",
    "type": "input",
    "occurrence": 1,
    "label": "WakaTime API key",
    "description": "Authenticates coding-activity sync when WakaTime is enabled."
  },
  {
    "id": "security.denied-commands",
    "labelKey": "pages.settings.securityPanel.denied_commands",
    "tab": "security",
    "type": "toggle",
    "occurrence": 1,
    "params": {
      "section": "rules"
    },
    "label": "Denied Commands"
  },
  {
    "id": "security.governance-policy",
    "labelKey": "pages.settings.securityPanel.governance_policy",
    "tab": "security",
    "type": "select",
    "occurrence": 1,
    "params": {
      "section": "governance"
    },
    "label": "Governance Policy"
  },
  {
    "id": "security.how-long-auto-approve-stays-on",
    "labelKey": "pages.settings.securityPanel.yolo_duration_title",
    "tab": "security",
    "type": "buttonGroup",
    "occurrence": 1,
    "params": {
      "section": "approval"
    },
    "configKey": "agent.yolo_duration",
    "label": "How long auto-approve stays on"
  },
  {
    "id": "security.live-security-posture",
    "labelKey": "pages.settings.securityPanel.live_security_posture",
    "tab": "security",
    "type": "toggle",
    "occurrence": 1,
    "params": {
      "section": "posture"
    },
    "label": "Live Security Posture"
  },
  {
    "id": "security.trust-every-third-party-app",
    "labelKey": "pages.settings.securityPanel.trustedApps.allow_all_label",
    "tab": "security",
    "type": "toggle",
    "occurrence": 1,
    "params": {
      "section": "apps"
    },
    "label": "Trust every third-party app",
    "description": "Off by default. When on, every third-party app you install can run its own code straight away, without asking you first."
  },
  {
    "id": "security.trust-this-machine-s-tailnet-name",
    "labelKey": "pages.settings.securityPanel.tailnet_title",
    "tab": "security",
    "type": "toggle",
    "occurrence": 1,
    "params": {
      "section": "tailnet"
    },
    "label": "Trust this machine's tailnet name"
  },
  {
    "id": "security.your-custom-denies",
    "labelKey": "pages.settings.securityPanel.your_custom_denies",
    "tab": "security",
    "type": "input",
    "occurrence": 1,
    "params": {
      "section": "rules"
    },
    "label": "Your custom denies",
    "description": "Add your own deny patterns (Python-compatible regex). These are enforced at {{productName}}'s PreToolUse gate alongside the built-in rules."
  },
  {
    "id": "shortcuts.enable-shortcuts",
    "label": "Enable shortcuts",
    "labelKey": "pages.settings.shortcutsPanel.enable_shortcuts",
    "tab": "shortcuts",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "shortcuts.search-everywhere",
    "label": "Search Everywhere",
    "labelKey": "components.shortcutsModal.search_everywhere",
    "tab": "shortcuts",
    "type": "buttonGroup",
    "occurrence": 1
  },
  {
    "id": "shortcuts.use-ctrl-not-option-for-chat-1-9",
    "label": "Use ⌃ Ctrl (not ⌥ Option) for chat 1–9",
    "labelKey": "pages.settings.shortcutsPanel.use_ctrl_not_option_for_chat_1_9",
    "description": "Bind chat-tab switching to Ctrl+digit instead of Option+digit",
    "tab": "shortcuts",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "skills.auto-generate-skills-from-sessions",
    "label": "Auto-generate skills from sessions",
    "labelKey": "pages.settings.skillsPanel.auto_generate_skills_from_sessions",
    "description": "Analyze each completed session and draft a reusable SKILL.md when the session demonstrates a recurring procedure — one a future session, working on a different target, would run again. Off by default. Drafts are staged to the pending queue on the Skills tab for review — nothing goes live without your approval (see below).",
    "tab": "skills",
    "type": "toggle",
    "occurrence": 1,
    "configKey": "skills.auto_create_from_sessions"
  },
  {
    "id": "skills.require-approval-before-generated-skills-go-live",
    "label": "Require approval before generated skills go live",
    "labelKey": "pages.settings.skillsPanel.require_approval_before_generated_skills_go_live",
    "description": "Keep every auto-generated candidate in the pending queue until you approve it. Turning this off lets prose-only skills publish automatically; skills that bundle scripts always require approval regardless.",
    "tab": "skills",
    "type": "toggle",
    "occurrence": 1,
    "configKey": "skills.approval_required"
  },
  {
    "id": "voice.auto-speak-responses",
    "label": "Auto-speak Responses",
    "labelKey": "pages.settings.voicePanel.auto_speak_responses",
    "description": "Speak every assistant reply automatically",
    "tab": "voice",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "voice.auto-submit-when-i-finish-speaking",
    "label": "Auto-submit when I finish speaking",
    "labelKey": "pages.settings.sttSettings.endpointing",
    "description": "Use a fast model to detect when you've finished a complete request and send it automatically. Streaming providers only.",
    "tab": "voice",
    "type": "toggle",
    "occurrence": 1,
    "configKey": "stt.endpointing"
  },
  {
    "id": "voice.aws-profile-amazon-polly",
    "label": "AWS Profile (Amazon Polly)",
    "labelKey": "pages.settings.voicePanel.aws_profile_polly",
    "description": "AWS credentials profile for Amazon Polly",
    "tab": "voice",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "voice.aws-profile-transcribe",
    "label": "AWS Profile (Transcribe)",
    "labelKey": "pages.settings.sttSettings.aws_profile_transcribe",
    "description": "AWS credentials profile for Transcribe (blank = default chain)",
    "tab": "voice",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "voice.aws-region-amazon-polly",
    "label": "AWS Region (Amazon Polly)",
    "labelKey": "pages.settings.voicePanel.aws_region_polly",
    "description": "AWS region for Amazon Polly API",
    "tab": "voice",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "voice.aws-region-transcribe",
    "label": "AWS Region (Transcribe)",
    "labelKey": "pages.settings.sttSettings.aws_region_transcribe",
    "description": "AWS region for Transcribe",
    "tab": "voice",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "voice.dictation-panel",
    "label": "Dictation panel",
    "labelKey": "pages.settings.sttSettings.dictation_panel",
    "description": "Show an animated panel while recording instead of the thin status bar. Falls back to the bar when the browser lacks WebGL2 or your system requests reduced motion.",
    "tab": "voice",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "voice.enabled",
    "label": "Enabled",
    "labelKey": "pages.settings.sttSettings.enabled",
    "description": "Transcribe voice into the message box when you click the mic",
    "tab": "voice",
    "type": "toggle",
    "occurrence": 1
  },
  {
    "id": "voice.engine",
    "label": "Engine",
    "labelKey": "pages.settings.voicePanel.engine",
    "description": "Amazon Polly engine type",
    "tab": "voice",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "voice.how-the-key-works",
    "label": "How the key works",
    "labelKey": "pages.settings.sttSettings.ptt_mode",
    "tab": "voice",
    "type": "buttonGroup",
    "occurrence": 1
  },
  {
    "id": "voice.language",
    "label": "Language",
    "labelKey": "pages.settings.sttSettings.language",
    "tab": "voice",
    "type": "select",
    "occurrence": 1,
    "configKey": "stt.language_code"
  },
  {
    "id": "voice.live-transcript-refresh-ms",
    "label": "Live transcript refresh (ms)",
    "labelKey": "pages.settings.sttSettings.partial_interval_ms",
    "description": "How often the transcript is redrawn while you speak. Lower feels more immediate and costs more processing.",
    "tab": "voice",
    "type": "stepper",
    "occurrence": 1,
    "configKey": "stt.partial_interval_ms"
  },
  {
    "id": "voice.microphone",
    "label": "Microphone",
    "labelKey": "pages.settings.sttSettings.microphone",
    "description": "Input device used to capture your voice",
    "tab": "voice",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "voice.model",
    "label": "Model",
    "labelKey": "pages.settings.sttSettings.model",
    "description": "Models download on demand. Select one and click Download now; the desktop app already includes every other runtime dependency.",
    "tab": "voice",
    "type": "select",
    "occurrence": 1,
    "configKey": "stt.model"
  },
  {
    "id": "voice.pause-that-ends-a-phrase-ms",
    "label": "Pause that ends a phrase (ms)",
    "labelKey": "pages.settings.sttSettings.silence_ms",
    "description": "How much silence commits what you just said. Lower reacts sooner; higher tolerates thinking pauses.",
    "tab": "voice",
    "type": "stepper",
    "occurrence": 1,
    "configKey": "stt.silence_ms"
  },
  {
    "id": "voice.piper-binary",
    "label": "Piper Binary",
    "labelKey": "pages.settings.voicePanel.piper_binary",
    "description": "Path to the piper executable. Leave blank to auto-detect on PATH or in a ~/piper-venv install",
    "tab": "voice",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "voice.piper-model",
    "label": "Piper Model",
    "labelKey": "pages.settings.voicePanel.piper_model",
    "description": "Path to the Piper voice model (.onnx). Required — download from huggingface.co/rhasspy/piper-voices",
    "tab": "voice",
    "type": "input",
    "occurrence": 1
  },
  {
    "id": "voice.provider",
    "label": "Provider",
    "labelKey": "pages.settings.sttSettings.provider",
    "description": "Local speech recognition runs on this machine and sends nothing anywhere. Transcribe uploads your audio to AWS.",
    "tab": "voice",
    "type": "select",
    "occurrence": 1,
    "configKey": "stt.provider"
  },
  {
    "id": "voice.provider-2",
    "label": "Provider",
    "labelKey": "pages.settings.voicePanel.provider",
    "description": "The built-in engine needs no setup; Piper is offline with better quality; Amazon Polly uses AWS credentials + network",
    "tab": "voice",
    "type": "select",
    "occurrence": 2,
    "settingId": "voice.provider-2"
  },
  {
    "id": "voice.shortcut-key",
    "label": "Shortcut key",
    "labelKey": "pages.settings.sttSettings.ptt_key",
    "tab": "voice",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "voice.speed",
    "label": "Speed",
    "labelKey": "pages.settings.voicePanel.speed",
    "description": "Speech rate for spoken replies (built-in engine)",
    "tab": "voice",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "voice.speed-2",
    "label": "Speed",
    "labelKey": "pages.settings.voicePanel.speed",
    "description": "Speech rate for spoken replies (Amazon Polly)",
    "tab": "voice",
    "type": "select",
    "occurrence": 2
  },
  {
    "id": "voice.speed-3",
    "label": "Speed",
    "labelKey": "pages.settings.voicePanel.speed",
    "description": "Piper speech speed (length scale)",
    "tab": "voice",
    "type": "select",
    "occurrence": 3
  },
  {
    "id": "voice.streaming",
    "label": "Streaming",
    "labelKey": "pages.settings.sttSettings.streaming",
    "description": "Show the transcript in the input box as you speak, instead of only when you stop.",
    "tab": "voice",
    "type": "toggle",
    "occurrence": 1,
    "configKey": "stt.streaming"
  },
  {
    "id": "voice.tap-vs-hold-cutoff",
    "label": "Tap vs. hold cutoff",
    "labelKey": "pages.settings.sttSettings.ptt_hold_threshold",
    "description": "Only used by “Both”. Hold the key longer than this to talk; a quicker tap starts recording and leaves it on.",
    "tab": "voice",
    "type": "stepper",
    "occurrence": 1
  },
  {
    "id": "voice.voice",
    "label": "Voice",
    "labelKey": "pages.settings.voicePanel.voice",
    "description": "Voice from the host's built-in speech engine",
    "tab": "voice",
    "type": "select",
    "occurrence": 1
  },
  {
    "id": "voice.voice-2",
    "label": "Voice",
    "labelKey": "pages.settings.voicePanel.voice",
    "description": "Amazon Polly voice for TTS",
    "tab": "voice",
    "type": "select",
    "occurrence": 2
  }
]
